p8105_hw2_cz2955
================
2025-09-23

## Problem 1

``` r
month_names <- c("Jan","Feb","Mar","Apr","May","Jun",
                   "Jul","Aug","Sep","Oct","Nov","Dec")
# clean pols_df
pols_df<-read_csv("pols-month.csv")|>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE)|> # convert: transfer"05"to"5"
  mutate(month = month_names[month])|>
  mutate(president=case_match(
    prez_gop,
    1 ~ "gop",
    0 ~ "dem"
    ))|>
  select(-prez_dem,-prez_gop)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# clean unemployment_df
unemployment_df<-read_csv("unemployment.csv")|>
  pivot_longer(
    Jan:Dec,
    names_to = "month",   # new column name 1st
    values_to = "unemployment_rate"  # new column name 2nd
  )|>
  rename(year = Year)|>
  arrange(year, month)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# clean snp_df
snp_df<-read_csv("snp.csv")|>
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) |>
  mutate(year=year+2000,month = month_names[month])|>
  arrange(year,month)|>
  relocate(year,month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# merge togrther
merge_df<-pols_df |>
  left_join(snp_df,by = c("year", "month"))|>
  left_join(unemployment_df,by = c("year", "month"))
```

Ans: The pols dataset contained monthly counts of national politicians
by party (Democratic and Republican), including variables such as
governors, senators, representatives, and the party of the sitting
president. The snp dataset recorded the closing value of the S&P 500
index by month. The unemployment dataset provided monthly unemployment
rates for the U.S. population. After cleaning and merging the three
datasets by year and month, we obtained a panel with dimensions 822 × 13
(depending on the range of years in the original files, typically from
the late 1947 through 2015 ). Key variables include year, month, day.x,
gov_gop, sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, president, day.y,
close, unemployment_rate.

## Problem 2

``` r
# Trash_wheel
trash_df<-readxl::read_excel("Trash-Wheel.xlsx")|>
  select(where(~!all(is.na(.))))|>
  rename(
    Dumpster = Dumpster,
    Month = Month,
    Year = Year,
    Date = Date,
    Weight_tons = `Weight (tons)`,
    Volume_cubic_yards = `Volume (cubic yards)`,
    Plastic_Bottles = `Plastic Bottles`,
    Polystyrene = Polystyrene,
    Cigarette_Butts = `Cigarette Butts`,
    Glass_Bottles = `Glass Bottles`,
    Plastic_Bags = `Plastic Bags`,
    Wrappers = Wrappers,
    Sports_Balls = `Sports Balls`,
    Homes_Powered = `Homes Powered*`
  )|>
  mutate(Sports_Balls=as.integer(round(Sports_Balls)))|>
  filter(!is.na(Weight_tons))|>
  filter(!is.na(Dumpster))|> 
  mutate(Year = as.integer(Year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
# Professor Trash Wheel
professor_df <- read_excel("Trash-Wheel.xlsx", sheet = 2)|>
    select(where(~!all(is.na(.))))|>
  filter(!if_all(everything(), ~ is.na(.)))|>
  filter(!(if_all(-1, is.na)))|>
  rename(
    Dumpster = Dumpster,
    Month = Month,
    Year = Year,
    Date = Date,
    Weight_tons = `Weight (tons)`,
    Volume_cubic_yards = `Volume (cubic yards)`,
    Plastic_Bottles = `Plastic Bottles`,
    Polystyrene = Polystyrene,
    Cigarette_Butts = `Cigarette Butts`,
    Glass_Bottles = `Glass Bottles`,
    Plastic_Bags = `Plastic Bags`,
    Wrappers = Wrappers,
    Homes_Powered = `Homes Powered*`
  )|>
  filter(!is.na(Dumpster))

# Gwynnda
gwynnda_df <- read_excel("Trash-Wheel.xlsx", sheet = 4)|>
    select(where(~!all(is.na(.))))|>
  filter(!if_all(everything(), ~ is.na(.)))|>
    rename(
    Dumpster = Dumpster,
    Month = Month,
    Year = Year,
    Date = Date,
    Weight_tons = `Weight (tons)`,
    Volume_cubic_yards = `Volume (cubic yards)`,
    Plastic_Bottles = `Plastic Bottles`,
    Polystyrene = Polystyrene,
    Cigarette_Butts = `Cigarette Butts`,
    Plastic_Bags = `Plastic Bags`,
    Wrappers = Wrappers,
    Homes_Powered = `Homes Powered*`
    )|>
  filter(!is.na(Dumpster))

together_df <- bind_rows(trash_df, professor_df, gwynnda_df)
```

In this study, we collated observational data from three Trash Wheels:
**Mr. Trash Wheel**, **Professor Trash Wheel**, and **Gwynnda**. The
combined dataset comprises 1188 observations, each containing the bin
number, date (year-month-day), and quantities of various waste types
such as plastic bottles (`Plastic_Bottles`), cigarette butts
(`Cigarette_Butts`), glass bottles (`Glass_Bottles`), and sports balls
(`Sports_Balls`).

According to the data, Professor Trash Wheel has collected 282.26 tonnes
of rubbish to date; while Gwynnda cleared 18120 cigarette butts in June
2022.

## Problem 3

``` r
zcodes<-read_csv("Zip_Codes.csv")|>
    select(County, ZipCode, Neighborhood) |>
  mutate(
    ZipCode = as.integer(ZipCode),
    County = as.character(County),
    Neighborhood = as.character(Neighborhood)
    )
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
znyc<-read_csv("Zip_NYC.csv")|>
  rename(ZipCode = RegionName,
         County = CountyName
         ) |>
  mutate(
    ZipCode = as.integer(ZipCode),
    County = str_replace(County, " County", "")
  )|>
  select(ZipCode, County, starts_with("201"), starts_with("202"))|>
  pivot_longer(
    cols = -c(ZipCode, County),
    names_to = "Date",
    values_to = "RentPrice"
  )
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
z_together <- znyc |>
  left_join(zcodes, by = c("ZipCode", "County"))
```

There are a total of 17284 observations, comprising 149 distinct
zipcodes and 43 different neighbourhoods.

The ZIP codes appear in the ZIP code dataset but not in the Zillow
Rental Price dataset is 10464, 10474, 10475, 10499, 10550, 10704, 10705,
10803, 11202, 11224, 11239, 11241, 11242, 11243, 11245, 11247, 11251,
11252, 11256, 10008, 10020, 10041, 10043, 10045, 10047, 10048, 10055,
10072, 10080, 10081, 10082, 10087, 10101, 10102, 10103, 10104, 10105,
10106, 10107, 10108, 10109, 10110, 10111, 10112, 10113, 10114, 10115,
10116, 10117, 10118, 10119, 10120, 10121, 10122, 10123, 10124, 10125,
10126, 10129, 10130, 10131, 10132, 10133, 10138, 10149, 10150, 10151,
10152, 10153, 10154, 10155, 10156, 10157, 10158, 10159, 10160, 10161,
10163, 10164, 10165, 10166, 10167, 10168, 10169, 10170, 10171, 10172,
10173, 10174, 10175, 10176, 10177, 10178, 10179, 10185, 10197, 10199,
10213, 10242, 10249, 10256, 10259, 10260, 10261, 10265, 10268, 10269,
10270, 10271, 10272, 10273, 10274, 10275, 10276, 10277, 10278, 10279,
10281, 10285, 10286, 10292, 11001, 11004, 11005, 11040, 11096, 11351,
11352, 11359, 11362, 11363, 11371, 11380, 11381, 11386, 11405, 11411,
11412, 11413, 11414, 11416, 11417, 11419, 11420, 11421, 11422, 11423,
11424, 11425, 11427, 11428, 11429, 11430, 11431, 11433, 11436, 11439,
11451, 11499, 11559, 11580, 11690, 11694, 11695, 11697, 10302, 10307,
10309, 10310, 10311, 10313. For instance, the Bronx zip codes 10464 and
10474 are primarily warehousing, industrial or port areas with no
residential rental properties, hence Zillow has no data for them.

### During the COVID-19 pandemic

``` r
z_compare <- z_together |>
  filter(Date %in% c("2020-01-31", "2021-01-31")) |>
  select(ZipCode, County, Neighborhood, Date, RentPrice)|>
  pivot_wider(
    names_from = Date,
    values_from = RentPrice,
    names_prefix = "Rent_"
  )|>
  rename(
    Rent_2020_01_31 = `Rent_2020-01-31`,
    Rent_2021_01_31 = `Rent_2021-01-31`
  )


T10_drop<-z_compare|>
  mutate(Diff_price=Rent_2021_01_31 - Rent_2020_01_31)|>
  arrange(Diff_price)|>
  select(ZipCode, 
         County, 
         Neighborhood, 
         Rent_2020_01_31, 
         Rent_2021_01_31, 
         Diff_price)|>
   slice(1:10)
T10_drop
```

    ## # A tibble: 10 × 6
    ##    ZipCode County   Neighborhood      Rent_2020_01_31 Rent_2021_01_31 Diff_price
    ##      <int> <chr>    <chr>                       <dbl>           <dbl>      <dbl>
    ##  1   10007 New York Lower Manhattan             6334.           5422.      -913.
    ##  2   10069 New York <NA>                        4623.           3875.      -748.
    ##  3   10009 New York Lower East Side             3406.           2692.      -714.
    ##  4   10016 New York Gramercy Park an…           3731.           3019.      -712.
    ##  5   10001 New York Chelsea and Clin…           4108.           3398.      -710.
    ##  6   10002 New York Lower East Side             3645.           2935.      -710.
    ##  7   10004 New York Lower Manhattan             3150.           2444.      -706.
    ##  8   10038 New York Lower Manhattan             3573.           2876.      -698.
    ##  9   10012 New York Greenwich Villag…           3629.           2942.      -686.
    ## 10   10010 New York Gramercy Park an…           3697.           3012.      -685.

As shown in the table, several core neighbourhoods in New York City
experienced significant rental declines between 2020 and 2021, with the
steepest drop to \$ 912.5965909 per month ( Lower Manhattan, 10007 ).
This reflects reduced demand stemming from population outflows, business
closures and the widespread adoption of remote working during the
COVID-19 pandemic.
